### ISSUE TITLE
stripchat.com

### ISSUE THREAD

**Issue by Hunterek** [dirk362/streamate-bash#2]
Im able to give you some info about stripchat.com they use hls for andorid device and it is able to download by using streamlink ex. https://hls-eu1.stripcdn.com/eu1/3394330_aac/playlist.m3u8?token=0f0ef6acbcd2c38ff3d9793a58709978
3394330 is ID model looks like token can be different cause working with other also, dont know where to find. 

BTW nice job with streamate working like champ on my ubuntu

**Comment by dirk362** [comment]
I've updated the code to incorporate several changes and improve stability, so master now includes a 'v2' of the streamate code.

If everything is working for you with the previous code release, I'd suggest you stick with that. Whilst the newer code is 'better', it adds no new functionality.

For stripchat.com, the token is defined per performer, with details obtained via a POST to a specific API URL on their servers. The streaming server relates to the region (continent and country), with a defined array of locations to servers (again obtained via their API). That said, this just defines which are allowed, as there is an assigned one to the performer via their set attributes when each session starts.
If time permits I may look into this, but no promises.
